apiVersion: v1
kind: Service
metadata:
  name: {{ include "honr.postgres.serviceName" . }}
  labels:
    {{- include "honr.labels" . | nindent 4 }}
    {{- include "honr.postgres.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "honr.postgres.selectorLabels" . | nindent 4 }}
